// Base de données — ~160 verbes avec toutes irrégularités
// type: "ar"|"er"|"ir"
// irregular: true  (si au moins un temps est irrégulier)
// participle: forme irrégulière du participe passé (si irrégulier)
// [tense]: { pronom: forme }  — seulement les formes qui dévient de la règle
// Pronoms : yo / tú / él / nosotros / vosotros / ellos
// (él couvre él/ella/usted, ellos couvre ellas/ustedes)

const V = {
  // ─── RÉGULIERS -AR ────────────────────────────────────────────
  hablar:     {type:"ar"},
  caminar:    {type:"ar"},
  trabajar:   {type:"ar"},
  escuchar:   {type:"ar"},
  mirar:      {type:"ar"},
  tomar:      {type:"ar"},
  comprar:    {type:"ar"},
  esperar:    {type:"ar"},
  entrar:     {type:"ar"},
  pasar:      {type:"ar"},
  dejar:      {type:"ar"},
  llevar:     {type:"ar"},
  llamar:     {type:"ar"},
  necesitar:  {type:"ar"},
  ayudar:     {type:"ar"},
  usar:       {type:"ar"},
  ganar:      {type:"ar"},
  cocinar:    {type:"ar"},
  limpiar:    {type:"ar"},
  preparar:   {type:"ar"},
  estudiar:   {type:"ar"},
  bailar:     {type:"ar"},
  cantar:     {type:"ar"},
  nadar:      {type:"ar"},
  descansar:  {type:"ar"},
  olvidar:    {type:"ar"},
  gastar:     {type:"ar"},
  terminar:   {type:"ar"},
  visitar:    {type:"ar"},
  explicar:   {type:"ar", irregular:true, indefinido:{yo:"expliqué"}},
  regar:      {type:"ar", irregular:true, indefinido:{yo:"regué"}, presente:{yo:"riego",tú:"riegas",él:"riega",ellos:"riegan"}},
  // Changement orthographique -car → -qué
  buscar:     {type:"ar", irregular:true, indefinido:{yo:"busqué"}},
  tocar:      {type:"ar", irregular:true, indefinido:{yo:"toqué"}},
  sacar:      {type:"ar", irregular:true, indefinido:{yo:"saqué"}},
  colocar:    {type:"ar", irregular:true, indefinido:{yo:"coloqué"}},
  // Changement orthographique -gar → -gué
  llegar:     {type:"ar", irregular:true, indefinido:{yo:"llegué"}},
  pagar:      {type:"ar", irregular:true, indefinido:{yo:"pagué"}},
  jugar:      {type:"ar", irregular:true, indefinido:{yo:"jugué"}, presente:{yo:"juego",tú:"juegas",él:"juega",ellos:"juegan"}, subjuntivo:{yo:"juegue",tú:"juegues",él:"juegue",nosotros:"juguemos",vosotros:"juguéis",ellos:"jueguen"}},
  entregar:   {type:"ar", irregular:true, indefinido:{yo:"entregué"}},
  // Changement orthographique -zar → -cé
  empezar:    {type:"ar", irregular:true, indefinido:{yo:"empecé"}, presente:{yo:"empiezo",tú:"empiezas",él:"empieza",ellos:"empiezan"}},
  comenzar:   {type:"ar", irregular:true, indefinido:{yo:"comencé"}, presente:{yo:"comienzo",tú:"comienzas",él:"comienza",ellos:"comienzan"}},
  almorzar:   {type:"ar", irregular:true, indefinido:{yo:"almorcé"}, presente:{yo:"almuerzo",tú:"almuerzas",él:"almuerza",ellos:"almuerzan"}},
  cruzar:     {type:"ar", irregular:true, indefinido:{yo:"crucé"}},
  rezar:      {type:"ar", irregular:true, indefinido:{yo:"recé"}},
  // Diphtongants o→ue
  recordar:   {type:"ar", irregular:true, presente:{yo:"recuerdo",tú:"recuerdas",él:"recuerda",ellos:"recuerdan"}},
  encontrar:  {type:"ar", irregular:true, presente:{yo:"encuentro",tú:"encuentras",él:"encuentra",ellos:"encuentran"}},
  contar:     {type:"ar", irregular:true, presente:{yo:"cuento",tú:"cuentas",él:"cuenta",ellos:"cuentan"}},
  mostrar:    {type:"ar", irregular:true, presente:{yo:"muestro",tú:"muestras",él:"muestra",ellos:"muestran"}},
  probar:     {type:"ar", irregular:true, presente:{yo:"pruebo",tú:"pruebas",él:"prueba",ellos:"prueban"}},
  volar:      {type:"ar", irregular:true, presente:{yo:"vuelo",tú:"vuelas",él:"vuela",ellos:"vuelan"}},
  costar:     {type:"ar", irregular:true, presente:{él:"cuesta",ellos:"cuestan"}},
  acostar:    {type:"ar", irregular:true, presente:{yo:"acuesto",tú:"acuestas",él:"acuesta",ellos:"acuestan"}},
  sonar:      {type:"ar", irregular:true, presente:{yo:"sueno",tú:"suenas",él:"suena",ellos:"suenan"}},
  apostar:    {type:"ar", irregular:true, presente:{yo:"apuesto",tú:"apuestas",él:"apuesta",ellos:"apuestan"}},
  rogar:      {type:"ar", irregular:true, presente:{yo:"ruego",tú:"ruegas",él:"ruega",ellos:"ruegan"}, indefinido:{yo:"rogué"}},
  // Diphtongants e→ie
  cerrar:     {type:"ar", irregular:true, presente:{yo:"cierro",tú:"cierras",él:"cierra",ellos:"cierran"}},
  pensar:     {type:"ar", irregular:true, presente:{yo:"pienso",tú:"piensas",él:"piensa",ellos:"piensan"}},
  despertar:  {type:"ar", irregular:true, presente:{yo:"despierto",tú:"despiertas",él:"despierta",ellos:"despiertan"}},
  sentar:     {type:"ar", irregular:true, presente:{yo:"siento",tú:"sientas",él:"sienta",ellos:"sientan"}},
  calentar:   {type:"ar", irregular:true, presente:{yo:"caliento",tú:"calientas",él:"calienta",ellos:"calientan"}},
  negar:      {type:"ar", irregular:true, presente:{yo:"niego",tú:"niegas",él:"niega",ellos:"niegan"}, indefinido:{yo:"negué"}},
  confesar:   {type:"ar", irregular:true, presente:{yo:"confieso",tú:"confiesas",él:"confiesa",ellos:"confiesan"}},
  atravesar:  {type:"ar", irregular:true, presente:{yo:"atravieso",tú:"atraviesas",él:"atraviesa",ellos:"atraviesan"}},
  gobernar:   {type:"ar", irregular:true, presente:{yo:"gobierno",tú:"gobiernas",él:"gobierna",ellos:"gobiernan"}},
  merendar:   {type:"ar", irregular:true, presente:{yo:"meriendo",tú:"meriendas",él:"merienda",ellos:"meriendan"}},
  viajar:     {type:"ar"},

  // ─── RÉGULIERS -ER ────────────────────────────────────────────
  comer:      {type:"er"},
  beber:      {type:"er"},
  correr:     {type:"er"},
  vender:     {type:"er"},
  aprender:   {type:"er"},
  comprender: {type:"er"},
  responder:  {type:"er"},
  romper:     {type:"er", participle:"roto"},
  deber:      {type:"er"},
  temer:      {type:"er"},
  barrer:     {type:"er"},
  meter:      {type:"er"},
  // -ER avec changement y (voyelle + -ió → -yó)
  leer:       {type:"er", irregular:true, indefinido:{él:"leyó",ellos:"leyeron"}, imperfecto:{}},
  creer:      {type:"er", irregular:true, indefinido:{él:"creyó",ellos:"creyeron"}},
  poseer:     {type:"er", irregular:true, indefinido:{él:"poseyó",ellos:"poseyeron"}},
  // Diphtongants o→ue
  volver:     {type:"er", irregular:true, presente:{yo:"vuelvo",tú:"vuelves",él:"vuelve",ellos:"vuelven"}, participle:"vuelto"},
  mover:      {type:"er", irregular:true, presente:{yo:"muevo",tú:"mueves",él:"mueve",ellos:"mueven"}},
  resolver:   {type:"er", irregular:true, presente:{yo:"resuelvo",tú:"resuelves",él:"resuelve",ellos:"resuelven"}, participle:"resuelto"},
  devolver:   {type:"er", irregular:true, presente:{yo:"devuelvo",tú:"devuelves",él:"devuelve",ellos:"devuelven"}, participle:"devuelto"},
  doler:      {type:"er", irregular:true, presente:{él:"duele",ellos:"duelen"}},
  llover:     {type:"er", irregular:true, presente:{él:"llueve"}},
  // Diphtongants e→ie
  entender:   {type:"er", irregular:true, presente:{yo:"entiendo",tú:"entiendes",él:"entiende",ellos:"entienden"}},
  perder:     {type:"er", irregular:true, presente:{yo:"pierdo",tú:"pierdes",él:"pierde",ellos:"pierden"}},
  querer:     {type:"er", irregular:true, presente:{yo:"quiero",tú:"quieres",él:"quiere",nosotros:"queremos",vosotros:"queréis",ellos:"quieren"}, indefinido:{yo:"quise",tú:"quisiste",él:"quiso",nosotros:"quisimos",vosotros:"quisisteis",ellos:"quisieron"}, futuro:{yo:"querré",tú:"querrás",él:"querrá",nosotros:"querremos",vosotros:"querréis",ellos:"querrán"}, condicional:{yo:"querría",tú:"querrías",él:"querría",nosotros:"querríamos",vosotros:"querríais",ellos:"querrían"}},
  encender:   {type:"er", irregular:true, presente:{yo:"enciendo",tú:"enciendes",él:"enciende",ellos:"encienden"}},
  defender:   {type:"er", irregular:true, presente:{yo:"defiendo",tú:"defiendes",él:"defiende",ellos:"defienden"}},
  // -cer → -zco
  conocer:    {type:"er", irregular:true, presente:{yo:"conozco"}, subjuntivo:{yo:"conozca",tú:"conozcas",él:"conozca",nosotros:"conozcamos",vosotros:"conozcáis",ellos:"conozcan"}},
  aparecer:   {type:"er", irregular:true, presente:{yo:"aparezco"}, subjuntivo:{yo:"aparezca",tú:"aparezcas",él:"aparezca",nosotros:"aparezcamos",vosotros:"aparezcáis",ellos:"aparezcan"}},
  ofrecer:    {type:"er", irregular:true, presente:{yo:"ofrezco"}, subjuntivo:{yo:"ofrezca",tú:"ofrezcas",él:"ofrezca",nosotros:"ofrezcamos",vosotros:"ofrezcáis",ellos:"ofrezcan"}},
  parecer:    {type:"er", irregular:true, presente:{yo:"parezco"}, subjuntivo:{yo:"parezca",tú:"parezcas",él:"parezca",nosotros:"parezcamos",vosotros:"parezcáis",ellos:"parezcan"}},
  nacer:      {type:"er", irregular:true, presente:{yo:"nazco"}, subjuntivo:{yo:"nazca",tú:"nazcas",él:"nazca",nosotros:"nazcamos",vosotros:"nazcáis",ellos:"nazcan"}},
  merecer:    {type:"er", irregular:true, presente:{yo:"merezco"}, subjuntivo:{yo:"merezca",tú:"merezcas",él:"merezca",nosotros:"merezcamos",vosotros:"merezcáis",ellos:"merezcan"}},
  pertenecer: {type:"er", irregular:true, presente:{yo:"pertenezco"}, subjuntivo:{yo:"pertenezca",tú:"pertenezcas",él:"pertenezca",nosotros:"pertenezcamos",vosotros:"pertenezcáis",ellos:"pertenezcan"}},
  agradecer:  {type:"er", irregular:true, presente:{yo:"agradezco"}, subjuntivo:{yo:"agradezca",tú:"agradezcas",él:"agradezca",nosotros:"agradezcamos",vosotros:"agradezcáis",ellos:"agradezcan"}},
  // Grands irréguliers -ER
  ser:        {type:"er", irregular:true, presente:{yo:"soy",tú:"eres",él:"es",nosotros:"somos",vosotros:"sois",ellos:"son"}, indefinido:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"}, imperfecto:{yo:"era",tú:"eras",él:"era",nosotros:"éramos",vosotros:"erais",ellos:"eran"}, futuro:{yo:"seré",tú:"serás",él:"será",nosotros:"seremos",vosotros:"seréis",ellos:"serán"}, condicional:{yo:"sería",tú:"serías",él:"sería",nosotros:"seríamos",vosotros:"seríais",ellos:"serían"}, subjuntivo:{yo:"sea",tú:"seas",él:"sea",nosotros:"seamos",vosotros:"seáis",ellos:"sean"}, subjuntivo_imperfecto:{yo:"fuera",tú:"fueras",él:"fuera",nosotros:"fuéramos",vosotros:"fuerais",ellos:"fueran"}, imperativo:{tú:"sé",nosotros:"seamos",vosotros:"sed",ellos:"sean"}},
  haber:      {type:"er", irregular:true, presente:{yo:"he",tú:"has",él:"ha",nosotros:"hemos",vosotros:"habéis",ellos:"han"}, indefinido:{yo:"hube",tú:"hubiste",él:"hubo",nosotros:"hubimos",vosotros:"hubisteis",ellos:"hubieron"}, imperfecto:{yo:"había",tú:"habías",él:"había",nosotros:"habíamos",vosotros:"habíais",ellos:"habían"}, futuro:{yo:"habré",tú:"habrás",él:"habrá",nosotros:"habremos",vosotros:"habréis",ellos:"habrán"}, condicional:{yo:"habría",tú:"habrías",él:"habría",nosotros:"habríamos",vosotros:"habríais",ellos:"habrían"}, subjuntivo:{yo:"haya",tú:"hayas",él:"haya",nosotros:"hayamos",vosotros:"hayáis",ellos:"hayan"}},
  poder:      {type:"er", irregular:true, presente:{yo:"puedo",tú:"puedes",él:"puede",nosotros:"podemos",vosotros:"podéis",ellos:"pueden"}, indefinido:{yo:"pude",tú:"pudiste",él:"pudo",nosotros:"pudimos",vosotros:"pudisteis",ellos:"pudieron"}, futuro:{yo:"podré",tú:"podrás",él:"podrá",nosotros:"podremos",vosotros:"podréis",ellos:"podrán"}, condicional:{yo:"podría",tú:"podrías",él:"podría",nosotros:"podríamos",vosotros:"podríais",ellos:"podrían"}, subjuntivo:{yo:"pueda",tú:"puedas",él:"pueda",nosotros:"podamos",vosotros:"podáis",ellos:"puedan"}},
  saber:      {type:"er", irregular:true, presente:{yo:"sé",tú:"sabes",él:"sabe",nosotros:"sabemos",vosotros:"sabéis",ellos:"saben"}, indefinido:{yo:"supe",tú:"supiste",él:"supo",nosotros:"supimos",vosotros:"supisteis",ellos:"supieron"}, futuro:{yo:"sabré",tú:"sabrás",él:"sabrá",nosotros:"sabremos",vosotros:"sabréis",ellos:"sabrán"}, condicional:{yo:"sabría",tú:"sabrías",él:"sabría",nosotros:"sabríamos",vosotros:"sabríais",ellos:"sabrían"}, subjuntivo:{yo:"sepa",tú:"sepas",él:"sepa",nosotros:"sepamos",vosotros:"sepáis",ellos:"sepan"}},
  ver:        {type:"er", irregular:true, presente:{yo:"veo",tú:"ves",él:"ve",nosotros:"vemos",vosotros:"veis",ellos:"ven"}, indefinido:{yo:"vi",tú:"viste",él:"vio",nosotros:"vimos",vosotros:"visteis",ellos:"vieron"}, imperfecto:{yo:"veía",tú:"veías",él:"veía",nosotros:"veíamos",vosotros:"veíais",ellos:"veían"}, subjuntivo:{yo:"vea",tú:"veas",él:"vea",nosotros:"veamos",vosotros:"veáis",ellos:"vean"}, participle:"visto"},
  hacer:      {type:"er", irregular:true, presente:{yo:"hago",tú:"haces",él:"hace",nosotros:"hacemos",vosotros:"hacéis",ellos:"hacen"}, indefinido:{yo:"hice",tú:"hiciste",él:"hizo",nosotros:"hicimos",vosotros:"hicisteis",ellos:"hicieron"}, futuro:{yo:"haré",tú:"harás",él:"hará",nosotros:"haremos",vosotros:"haréis",ellos:"harán"}, condicional:{yo:"haría",tú:"harías",él:"haría",nosotros:"haríamos",vosotros:"haríais",ellos:"harían"}, subjuntivo:{yo:"haga",tú:"hagas",él:"haga",nosotros:"hagamos",vosotros:"hagáis",ellos:"hagan"}, imperativo:{tú:"haz",nosotros:"hagamos",vosotros:"haced",ellos:"hagan"}, participle:"hecho"},
  poner:      {type:"er", irregular:true, presente:{yo:"pongo",tú:"pones",él:"pone",nosotros:"ponemos",vosotros:"ponéis",ellos:"ponen"}, indefinido:{yo:"puse",tú:"pusiste",él:"puso",nosotros:"pusimos",vosotros:"pusisteis",ellos:"pusieron"}, futuro:{yo:"pondré",tú:"pondrás",él:"pondrá",nosotros:"pondremos",vosotros:"pondréis",ellos:"pondrán"}, condicional:{yo:"pondría",tú:"pondrías",él:"pondría",nosotros:"pondríamos",vosotros:"pondríais",ellos:"pondrían"}, subjuntivo:{yo:"ponga",tú:"pongas",él:"ponga",nosotros:"pongamos",vosotros:"pongáis",ellos:"pongan"}, imperativo:{tú:"pon",nosotros:"pongamos",vosotros:"poned",ellos:"pongan"}, participle:"puesto"},
  tener:      {type:"er", irregular:true, presente:{yo:"tengo",tú:"tienes",él:"tiene",nosotros:"tenemos",vosotros:"tenéis",ellos:"tienen"}, indefinido:{yo:"tuve",tú:"tuviste",él:"tuvo",nosotros:"tuvimos",vosotros:"tuvisteis",ellos:"tuvieron"}, futuro:{yo:"tendré",tú:"tendrás",él:"tendrá",nosotros:"tendremos",vosotros:"tendréis",ellos:"tendrán"}, condicional:{yo:"tendría",tú:"tendrías",él:"tendría",nosotros:"tendríamos",vosotros:"tendríais",ellos:"tendrían"}, subjuntivo:{yo:"tenga",tú:"tengas",él:"tenga",nosotros:"tengamos",vosotros:"tengáis",ellos:"tengan"}, imperativo:{tú:"ten",nosotros:"tengamos",vosotros:"tened",ellos:"tengan"}},
  traer:      {type:"er", irregular:true, presente:{yo:"traigo",tú:"traes",él:"trae",nosotros:"traemos",vosotros:"traéis",ellos:"traen"}, indefinido:{yo:"traje",tú:"trajiste",él:"trajo",nosotros:"trajimos",vosotros:"trajisteis",ellos:"trajeron"}, subjuntivo:{yo:"traiga",tú:"traigas",él:"traiga",nosotros:"traigamos",vosotros:"traigáis",ellos:"traigan"}},
  caer:       {type:"er", irregular:true, presente:{yo:"caigo",tú:"caes",él:"cae",nosotros:"caemos",vosotros:"caéis",ellos:"caen"}, indefinido:{yo:"caí",tú:"caíste",él:"cayó",nosotros:"caímos",vosotros:"caísteis",ellos:"cayeron"}, subjuntivo:{yo:"caiga",tú:"caigas",él:"caiga",nosotros:"caigamos",vosotros:"caigáis",ellos:"caigan"}},
  caber:      {type:"er", irregular:true, presente:{yo:"quepo",tú:"cabes",él:"cabe",nosotros:"cabemos",vosotros:"cabéis",ellos:"caben"}, indefinido:{yo:"cupe",tú:"cupiste",él:"cupo",nosotros:"cupimos",vosotros:"cupisteis",ellos:"cupieron"}, futuro:{yo:"cabré",tú:"cabrás",él:"cabrá",nosotros:"cabremos",vosotros:"cabréis",ellos:"cabrán"}, condicional:{yo:"cabría",tú:"cabrías",él:"cabría",nosotros:"cabríamos",vosotros:"cabríais",ellos:"cabrían"}, subjuntivo:{yo:"quepa",tú:"quepas",él:"quepa",nosotros:"quepamos",vosotros:"quepáis",ellos:"quepan"}},
  valer:      {type:"er", irregular:true, presente:{yo:"valgo",tú:"vales",él:"vale",nosotros:"valemos",vosotros:"valéis",ellos:"valen"}, futuro:{yo:"valdré",tú:"valdrás",él:"valdrá",nosotros:"valdremos",vosotros:"valdréis",ellos:"valdrán"}, condicional:{yo:"valdría",tú:"valdrías",él:"valdría",nosotros:"valdríamos",vosotros:"valdríais",ellos:"valdrían"}, subjuntivo:{yo:"valga",tú:"valgas",él:"valga",nosotros:"valgamos",vosotros:"valgáis",ellos:"valgan"}},
  obtener:    {type:"er", irregular:true, presente:{yo:"obtengo",tú:"obtienes",él:"obtiene",nosotros:"obtenemos",vosotros:"obtenéis",ellos:"obtienen"}, indefinido:{yo:"obtuve",tú:"obtuviste",él:"obtuvo",nosotros:"obtuvimos",vosotros:"obtuvisteis",ellos:"obtuvieron"}, futuro:{yo:"obtendré",tú:"obtendrás",él:"obtendrá",nosotros:"obtendremos",vosotros:"obtendréis",ellos:"obtendrán"}, condicional:{yo:"obtendría",tú:"obtendrías",él:"obtendría",nosotros:"obtendríamos",vosotros:"obtendríais",ellos:"obtendrían"}, subjuntivo:{yo:"obtenga",tú:"obtengas",él:"obtenga",nosotros:"obtengamos",vosotros:"obtengáis",ellos:"obtengan"}},
  contener:   {type:"er", irregular:true, presente:{yo:"contengo",tú:"contienes",él:"contiene",nosotros:"contenemos",vosotros:"contenéis",ellos:"contienen"}, indefinido:{yo:"contuve",tú:"contuviste",él:"contuvo",nosotros:"contuvimos",vosotros:"contuvisteis",ellos:"contuvieron"}, futuro:{yo:"contendré",tú:"contendrás",él:"contendrá",nosotros:"contendremos",vosotros:"contendréis",ellos:"contendrán"}, condicional:{yo:"contendría",tú:"contendrías",él:"contendría",nosotros:"contendríamos",vosotros:"contendríais",ellos:"contendrían"}},

  // ─── RÉGULIERS -IR ────────────────────────────────────────────
  vivir:      {type:"ir"},
  abrir:      {type:"ir", participle:"abierto"},
  subir:      {type:"ir"},
  recibir:    {type:"ir"},
  decidir:    {type:"ir"},
  discutir:   {type:"ir"},
  permitir:   {type:"ir"},
  existir:    {type:"ir"},
  dividir:    {type:"ir"},
  // -IR changement orthographique -gir → -jo
  dirigir:    {type:"ir", irregular:true, presente:{yo:"dirijo"}, subjuntivo:{yo:"dirija",tú:"dirijas",él:"dirija",nosotros:"dirijamos",vosotros:"dirijáis",ellos:"dirijan"}},
  elegir:     {type:"ir", irregular:true, presente:{yo:"elijo",tú:"eliges",él:"elige",nosotros:"elegimos",vosotros:"elegís",ellos:"eligen"}, indefinido:{yo:"elegí",tú:"elegiste",él:"eligió",nosotros:"elegimos",vosotros:"elegisteis",ellos:"eligieron"}, subjuntivo:{yo:"elija",tú:"elijas",él:"elija",nosotros:"elijamos",vosotros:"elijáis",ellos:"elijan"}},
  exigir:     {type:"ir", irregular:true, presente:{yo:"exijo"}, subjuntivo:{yo:"exija",tú:"exijas",él:"exija",nosotros:"exijamos",vosotros:"exijáis",ellos:"exijan"}},
  // Alternance e→i
  pedir:      {type:"ir", irregular:true, presente:{yo:"pido",tú:"pides",él:"pide",nosotros:"pedimos",vosotros:"pedís",ellos:"piden"}, indefinido:{yo:"pedí",tú:"pediste",él:"pidió",nosotros:"pedimos",vosotros:"pedisteis",ellos:"pidieron"}, subjuntivo:{yo:"pida",tú:"pidas",él:"pida",nosotros:"pidamos",vosotros:"pidáis",ellos:"pidan"}},
  seguir:     {type:"ir", irregular:true, presente:{yo:"sigo",tú:"sigues",él:"sigue",nosotros:"seguimos",vosotros:"seguís",ellos:"siguen"}, indefinido:{yo:"seguí",tú:"seguiste",él:"siguió",nosotros:"seguimos",vosotros:"seguisteis",ellos:"siguieron"}, subjuntivo:{yo:"siga",tú:"sigas",él:"siga",nosotros:"sigamos",vosotros:"sigáis",ellos:"sigan"}},
  servir:     {type:"ir", irregular:true, presente:{yo:"sirvo",tú:"sirves",él:"sirve",nosotros:"servimos",vosotros:"servís",ellos:"sirven"}, indefinido:{yo:"serví",tú:"serviste",él:"sirvió",nosotros:"servimos",vosotros:"servisteis",ellos:"sirvieron"}, subjuntivo:{yo:"sirva",tú:"sirvas",él:"sirva",nosotros:"sirvamos",vosotros:"sirváis",ellos:"sirvan"}},
  vestir:     {type:"ir", irregular:true, presente:{yo:"visto",tú:"vistes",él:"viste",nosotros:"vestimos",vosotros:"vestís",ellos:"visten"}, indefinido:{yo:"vestí",tú:"vestiste",él:"vistió",nosotros:"vestimos",vosotros:"vestisteis",ellos:"vistieron"}, subjuntivo:{yo:"vista",tú:"vistas",él:"vista",nosotros:"vistamos",vosotros:"vistáis",ellos:"vistan"}},
  repetir:    {type:"ir", irregular:true, presente:{yo:"repito",tú:"repites",él:"repite",nosotros:"repetimos",vosotros:"repetís",ellos:"repiten"}, indefinido:{yo:"repetí",tú:"repetiste",él:"repitió",nosotros:"repetimos",vosotros:"repetisteis",ellos:"repitieron"}},
  medir:      {type:"ir", irregular:true, presente:{yo:"mido",tú:"mides",él:"mide",nosotros:"medimos",vosotros:"medís",ellos:"miden"}, indefinido:{yo:"medí",tú:"mediste",él:"midió",nosotros:"medimos",vosotros:"medisteis",ellos:"midieron"}},
  // Diphtongants e→ie et e→i (double irrégularité)
  sentir:     {type:"ir", irregular:true, presente:{yo:"siento",tú:"sientes",él:"siente",nosotros:"sentimos",vosotros:"sentís",ellos:"sienten"}, indefinido:{yo:"sentí",tú:"sentiste",él:"sintió",nosotros:"sentimos",vosotros:"sentisteis",ellos:"sintieron"}, subjuntivo:{yo:"sienta",tú:"sientas",él:"sienta",nosotros:"sintamos",vosotros:"sintáis",ellos:"sientan"}},
  mentir:     {type:"ir", irregular:true, presente:{yo:"miento",tú:"mientes",él:"miente",nosotros:"mentimos",vosotros:"mentís",ellos:"mienten"}, indefinido:{yo:"mentí",tú:"mentiste",él:"mintió",nosotros:"mentimos",vosotros:"mentisteis",ellos:"mintieron"}},
  preferir:   {type:"ir", irregular:true, presente:{yo:"prefiero",tú:"prefieres",él:"prefiere",nosotros:"preferimos",vosotros:"preferís",ellos:"prefieren"}, indefinido:{yo:"preferí",tú:"preferiste",él:"prefirió",nosotros:"preferimos",vosotros:"preferisteis",ellos:"prefirieron"}},
  sugerir:    {type:"ir", irregular:true, presente:{yo:"sugiero",tú:"sugieres",él:"sugiere",nosotros:"sugerimos",vosotros:"sugerís",ellos:"sugieren"}, indefinido:{yo:"sugerí",tú:"sugeriste",él:"sugirió",nosotros:"sugerimos",vosotros:"sugeristeis",ellos:"sugirieron"}},
  // Diphtongants o→ue et o→u
  dormir:     {type:"ir", irregular:true, presente:{yo:"duermo",tú:"duermes",él:"duerme",nosotros:"dormimos",vosotros:"dormís",ellos:"duermen"}, indefinido:{yo:"dormí",tú:"dormiste",él:"durmió",nosotros:"dormimos",vosotros:"dormisteis",ellos:"durmieron"}, subjuntivo:{yo:"duerma",tú:"duermas",él:"duerma",nosotros:"durmamos",vosotros:"durmáis",ellos:"duerman"}},
  morir:      {type:"ir", irregular:true, presente:{yo:"muero",tú:"mueres",él:"muere",nosotros:"morimos",vosotros:"morís",ellos:"mueren"}, indefinido:{yo:"morí",tú:"moriste",él:"murió",nosotros:"morimos",vosotros:"moristeis",ellos:"murieron"}, participle:"muerto"},
  // -uir → -uyo
  construir:  {type:"ir", irregular:true, presente:{yo:"construyo",tú:"construyes",él:"construye",nosotros:"construimos",vosotros:"construís",ellos:"construyen"}, indefinido:{yo:"construí",tú:"construiste",él:"construyó",nosotros:"construimos",vosotros:"construisteis",ellos:"construyeron"}, subjuntivo:{yo:"construya",tú:"construyas",él:"construya",nosotros:"construyamos",vosotros:"construyáis",ellos:"construyan"}},
  distribuir: {type:"ir", irregular:true, presente:{yo:"distribuyo",tú:"distribuyes",él:"distribuye",nosotros:"distribuimos",vosotros:"distribuís",ellos:"distribuyen"}, indefinido:{yo:"distribuí",tú:"distribuiste",él:"distribuyó",nosotros:"distribuimos",vosotros:"distribuisteis",ellos:"distribuyeron"}},
  huir:       {type:"ir", irregular:true, presente:{yo:"huyo",tú:"huyes",él:"huye",nosotros:"huimos",vosotros:"huís",ellos:"huyen"}, indefinido:{yo:"huí",tú:"huiste",él:"huyó",nosotros:"huimos",vosotros:"huisteis",ellos:"huyeron"}},
  incluir:    {type:"ir", irregular:true, presente:{yo:"incluyo",tú:"incluyes",él:"incluye",nosotros:"incluimos",vosotros:"incluís",ellos:"incluyen"}, indefinido:{yo:"incluí",tú:"incluiste",él:"incluyó",nosotros:"incluimos",vosotros:"incluisteis",ellos:"incluyeron"}},
  concluir:   {type:"ir", irregular:true, presente:{yo:"concluyo",tú:"concluyes",él:"concluye",nosotros:"concluimos",vosotros:"concluís",ellos:"concluyen"}, indefinido:{yo:"concluí",tú:"concluiste",él:"concluyó",nosotros:"concluimos",vosotros:"concluisteis",ellos:"concluyeron"}},
  // -cir → -zco
  conducir:   {type:"ir", irregular:true, presente:{yo:"conduzco"}, indefinido:{yo:"conduje",tú:"condujiste",él:"condujo",nosotros:"condujimos",vosotros:"condujisteis",ellos:"condujeron"}, subjuntivo:{yo:"conduzca",tú:"conduzcas",él:"conduzca",nosotros:"conduzcamos",vosotros:"conduzcáis",ellos:"conduzcan"}},
  producir:   {type:"ir", irregular:true, presente:{yo:"produzco"}, indefinido:{yo:"produje",tú:"produjiste",él:"produjo",nosotros:"produjimos",vosotros:"produjisteis",ellos:"produjeron"}, subjuntivo:{yo:"produzca",tú:"produzcas",él:"produzca",nosotros:"produzcamos",vosotros:"produzcáis",ellos:"produzcan"}},
  traducir:   {type:"ir", irregular:true, presente:{yo:"traduzco"}, indefinido:{yo:"traduje",tú:"tradujiste",él:"tradujo",nosotros:"tradujimos",vosotros:"tradujisteis",ellos:"tradujeron"}, subjuntivo:{yo:"traduzca",tú:"traduzcas",él:"traduzca",nosotros:"traduzcamos",vosotros:"traduzcáis",ellos:"traduzcan"}},
  reducir:    {type:"ir", irregular:true, presente:{yo:"reduzco"}, indefinido:{yo:"reduje",tú:"redujiste",él:"redujo",nosotros:"redujimos",vosotros:"redujisteis",ellos:"redujeron"}},
  // Grands irréguliers -IR
  ir:         {type:"ir", irregular:true, presente:{yo:"voy",tú:"vas",él:"va",nosotros:"vamos",vosotros:"vais",ellos:"van"}, indefinido:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"}, imperfecto:{yo:"iba",tú:"ibas",él:"iba",nosotros:"íbamos",vosotros:"ibais",ellos:"iban"}, futuro:{yo:"iré",tú:"irás",él:"irá",nosotros:"iremos",vosotros:"iréis",ellos:"irán"}, condicional:{yo:"iría",tú:"irías",él:"iría",nosotros:"iríamos",vosotros:"iríais",ellos:"irían"}, subjuntivo:{yo:"vaya",tú:"vayas",él:"vaya",nosotros:"vayamos",vosotros:"vayáis",ellos:"vayan"}, subjuntivo_imperfecto:{yo:"fuera",tú:"fueras",él:"fuera",nosotros:"fuéramos",vosotros:"fuerais",ellos:"fueran"}, imperativo:{tú:"ve",nosotros:"vayamos",vosotros:"id",ellos:"vayan"}},
  venir:      {type:"ir", irregular:true, presente:{yo:"vengo",tú:"vienes",él:"viene",nosotros:"venimos",vosotros:"venís",ellos:"vienen"}, indefinido:{yo:"vine",tú:"viniste",él:"vino",nosotros:"vinimos",vosotros:"vinisteis",ellos:"vinieron"}, futuro:{yo:"vendré",tú:"vendrás",él:"vendrá",nosotros:"vendremos",vosotros:"vendréis",ellos:"vendrán"}, condicional:{yo:"vendría",tú:"vendrías",él:"vendría",nosotros:"vendríamos",vosotros:"vendríais",ellos:"vendrían"}, subjuntivo:{yo:"venga",tú:"vengas",él:"venga",nosotros:"vengamos",vosotros:"vengáis",ellos:"vengan"}, imperativo:{tú:"ven",nosotros:"vengamos",vosotros:"venid",ellos:"vengan"}},
  decir:      {type:"ir", irregular:true, presente:{yo:"digo",tú:"dices",él:"dice",nosotros:"decimos",vosotros:"decís",ellos:"dicen"}, indefinido:{yo:"dije",tú:"dijiste",él:"dijo",nosotros:"dijimos",vosotros:"dijisteis",ellos:"dijeron"}, futuro:{yo:"diré",tú:"dirás",él:"dirá",nosotros:"diremos",vosotros:"diréis",ellos:"dirán"}, condicional:{yo:"diría",tú:"dirías",él:"diría",nosotros:"diríamos",vosotros:"diríais",ellos:"dirían"}, subjuntivo:{yo:"diga",tú:"digas",él:"diga",nosotros:"digamos",vosotros:"digáis",ellos:"digan"}, imperativo:{tú:"di",nosotros:"digamos",vosotros:"decid",ellos:"digan"}, participle:"dicho"},
  salir:      {type:"ir", irregular:true, presente:{yo:"salgo",tú:"sales",él:"sale",nosotros:"salimos",vosotros:"salís",ellos:"salen"}, indefinido:{yo:"salí",tú:"saliste",él:"salió",nosotros:"salimos",vosotros:"salisteis",ellos:"salieron"}, futuro:{yo:"saldré",tú:"saldrás",él:"saldrá",nosotros:"saldremos",vosotros:"saldréis",ellos:"saldrán"}, condicional:{yo:"saldría",tú:"saldrías",él:"saldría",nosotros:"saldríamos",vosotros:"saldríais",ellos:"saldrían"}, subjuntivo:{yo:"salga",tú:"salgas",él:"salga",nosotros:"salgamos",vosotros:"salgáis",ellos:"salgan"}, imperativo:{tú:"sal",nosotros:"salgamos",vosotros:"salid",ellos:"salgan"}},
  estar:      {type:"ar", irregular:true, presente:{yo:"estoy",tú:"estás",él:"está",nosotros:"estamos",vosotros:"estáis",ellos:"están"}, indefinido:{yo:"estuve",tú:"estuviste",él:"estuvo",nosotros:"estuvimos",vosotros:"estuvisteis",ellos:"estuvieron"}, imperfecto:{yo:"estaba",tú:"estabas",él:"estaba",nosotros:"estábamos",vosotros:"estabais",ellos:"estaban"}, futuro:{yo:"estaré",tú:"estarás",él:"estará",nosotros:"estaremos",vosotros:"estaréis",ellos:"estarán"}, condicional:{yo:"estaría",tú:"estarías",él:"estaría",nosotros:"estaríamos",vosotros:"estaríais",ellos:"estarían"}, subjuntivo:{yo:"esté",tú:"estés",él:"esté",nosotros:"estemos",vosotros:"estéis",ellos:"estén"}, subjuntivo_imperfecto:{yo:"estuviera",tú:"estuvieras",él:"estuviera",nosotros:"estuviéramos",vosotros:"estuvierais",ellos:"estuvieran"}, imperativo:{tú:"está",nosotros:"estemos",vosotros:"estad",ellos:"estén"}},
  dar:        {type:"ar", irregular:true, presente:{yo:"doy",tú:"das",él:"da",nosotros:"damos",vosotros:"dais",ellos:"dan"}, indefinido:{yo:"di",tú:"diste",él:"dio",nosotros:"dimos",vosotros:"disteis",ellos:"dieron"}, imperfecto:{yo:"daba",tú:"dabas",él:"daba",nosotros:"dábamos",vosotros:"dabais",ellos:"daban"}, subjuntivo:{yo:"dé",tú:"des",él:"dé",nosotros:"demos",vosotros:"deis",ellos:"den"}, subjuntivo_imperfecto:{yo:"diera",tú:"dieras",él:"diera",nosotros:"diéramos",vosotros:"dierais",ellos:"dieran"}},
  escribir:   {type:"ir", participle:"escrito"},
  cubrir:     {type:"ir", participle:"cubierto"},
  oír:        {type:"ir", irregular:true, presente:{yo:"oigo",tú:"oyes",él:"oye",nosotros:"oímos",vosotros:"oís",ellos:"oyen"}, indefinido:{yo:"oí",tú:"oíste",él:"oyó",nosotros:"oímos",vosotros:"oísteis",ellos:"oyeron"}, imperfecto:{yo:"oía",tú:"oías",él:"oía",nosotros:"oíamos",vosotros:"oíais",ellos:"oían"}, subjuntivo:{yo:"oiga",tú:"oigas",él:"oiga",nosotros:"oigamos",vosotros:"oigáis",ellos:"oigan"}},
  reír:       {type:"ir", irregular:true, presente:{yo:"río",tú:"ríes",él:"ríe",nosotros:"reímos",vosotros:"reís",ellos:"ríen"}, indefinido:{yo:"reí",tú:"reíste",él:"rió",nosotros:"reímos",vosotros:"reísteis",ellos:"rieron"}, subjuntivo:{yo:"ría",tú:"rías",él:"ría",nosotros:"riamos",vosotros:"riáis",ellos:"rían"}},
  sonreír:    {type:"ir", irregular:true, presente:{yo:"sonrío",tú:"sonríes",él:"sonríe",nosotros:"sonreímos",vosotros:"sonreís",ellos:"sonríen"}, indefinido:{yo:"sonreí",tú:"sonreíste",él:"sonrió",nosotros:"sonreímos",vosotros:"sonreísteis",ellos:"sonrieron"}},
};


